### ISSUE TITLE
cannot create apk

### ISSUE THREAD

**Issue by ahhl** [slashmax/AAMirror#11]
why i cannot create debug. apk anymore?
sorry. first time using android studio

**Comment by slashmax** [comment]
can u post the error u get?

**Comment by inialsien** [comment]
@ahhl 

> You also need to rename the application package name (in app/build.gradle) and [obtain google-services.json](https://developers.google.com/mobile/add), and put it in app/. 

check [this](https://github.com/martoreto/aastats)

**Comment by ahhl** [comment]
thank for advice. thanks slashmax for inserting again the apk-debug.
i really do not know how to code.
