### ISSUE TITLE
Audio and  brightness control

### ISSUE THREAD

**Issue by bbsskk** [slashmax/AAMirror#12]
Thank you for this wonderfull app you developed

I've really enjoyed thesedays.

I have just some issues that I want you to upgrade
When I start a AA Mirror with my GPS app, the sound doesn't come out
After moving to the audio tab on AA and playing a song, then the sound from GPS app comes out

And I want you to add an option to restore brightness value setting after unplugging the phone.

Thank you

**Comment by slashmax** [comment]
should be fixed
