### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by Abdull10** [slashmax/AAMirror#15]
I have installed the app from someone provided me the apk file. When I run the app, it opens but It is only white screen with nothing to do or change. No settings.. Nothing. I connected AA in my car, and I found AA mirror, when I click on it, it gives black screen.

**Comment by seogi1004** [comment]
Android auto app problem.
Please use version 2.9.x.

**Comment by Abdull10** [comment]
I am already using AA ver 2.9. And I still face this problem. The AAmirror its self when I opened it after installation does not show its setting. It open and gives me white screen.

**Comment by seogi1004** [comment]
Please erase all the configuration information and install it again.

**Comment by Abdull10** [comment]
Which confg. And how to erase it?

**Comment by slashmax** [comment]
its an old version

**Comment by Abdull10** [comment]
I am using the latest app. It is not working as i mentioned above.

**Comment by bandrojic** [comment]
I have the same problem.....maybe anybody have solution with step description?
