### ISSUE TITLE
Touch screen

### ISSUE THREAD

**Issue by waw555** [slashmax/AAMirror#2]
It is necessary to add the possibility of using the sensor from the head unit
You need to add audio output from the applications to the head unit
Remove the bottom bar of Android Auto

**Comment by pippo45454** [comment]
is it possible to manage the applications directly from the radio screen with the touchscreen?

**Comment by waw555** [comment]
No

**Comment by waw555** [comment]
Only phone screen

**Comment by slashmax** [comment]
Touch control requires root.
You might need to switch audio source to AA from head unit if it doesn't switch automatically.
Bottom bar can't be removed.
