### ISSUE TITLE
App not showing on AA 3.0

### ISSUE THREAD

**Issue by matisaul** [slashmax/AAMirror#20]
I installed the apk, but in AA 3.0 is not showing on my car.

**Comment by alexfocus** [comment]
> I installed the apk, but in AA 3.0 is not showing on my car.

Google in version 3.0 banned applications without installing through GooglePlay
Use version 2.9, or install the application on 3.0 via adb:
1. Turn on debugging over USB.
2. Allow the computer to debug
2. Сopy the app to internal memory and run:
`adb shell pm install -i "com.android.vending" -r /sdcard/app-debug.apk`

**Comment by matisaul** [comment]
Thanks for your reply. I try that way, AAMirror shows on AA, but it shows only a black screen. I have Android 7.0 with root, and lastest AA app.

**Comment by MrJH76** [comment]
I used AAMirror well in AA 3.0 using the adb command. However, when I install a new AAMirror(2018.3.23), I do not see AAMirror in select menu.

**Comment by slashmax** [comment]
3rd party app not signed by google are blocked for now. Unblock will require root in future.
