### ISSUE TITLE
Google maps

### ISSUE THREAD

**Issue by gigibindi** [slashmax/AAMirror#24]
Hi i'm using AAMirror with Android Auto 2.9.574924
When i open the GOOGLE MAPS app from the display of the car, android auto open the app "MAPS SIMPLIFIED" for the car and not the GOOGLE MAPS app of the smartphone (please see the video https://streamable.com/xbnf9  )
Is possible to fix?
Thanks

**Comment by slashmax** [comment]
dont think so
