### ISSUE TITLE
Samsung SM-G800F Android 6.0.1 root not working

### ISSUE THREAD

**Issue by LavSug** [slashmax/AAMirror#28]
Hello!
I've tryed many time, but my device still doesn't working :( 
I installed AnAuto from Play Market and installed AAMirrow through adb.
As result I got black window :( But when I touch my phone get touching.
What may be wrong?
![desktop](https://user-images.githubusercontent.com/24413697/37772842-8b48bbce-2de4-11e8-89f9-93cfb8eee2cd.png)
![screenshot_2018-03-22-16-06-30](https://user-images.githubusercontent.com/24413697/37772845-8dc61a5e-2de4-11e8-9022-1edf70b28fd4.png)

**Comment by ahhl** [comment]
have you granted all the permission request on the phone, when you launch aamirror first time?

**Comment by LavSug** [comment]
Of course. There was only one permission request from SuperSU and one request for monitor capture.

**Comment by LavSug** [comment]
https://github.com/slashmax/AAMirror/commit/c5349e63721246987eebe526d53f32594149433a
This is the latest workable release on my device...

**Comment by LavSug** [comment]
I've found the issue. I've tested all commits and found that excluding m_SurfaceView.getHolder().setFormat(PixelFormat.RGBA_8888); 
generate my problem. I don't know why but it's really so:))))

**Comment by slashmax** [comment]
i cant support forks, the code line u posted isnt there anymore. try last comit.

**Comment by LavSug** [comment]
It's not a fork... Don't see at the picture. Try to see your 6 and 7 commits...
