### ISSUE TITLE
Screen Resolution

### ISSUE THREAD

**Issue by VantageT** [slashmax/AAMirror#3]
Image does not fill the screen perfectly. Still investigating to see if it is a phone or stereo issue.

**Comment by slashmax** [comment]
screen resize coming soon for rooted phones

**Comment by VantageT** [comment]
Ok thank you. Your work has been great with this app!

**Comment by yeonho** [comment]
i have no rooted phone.
but i am very curious how it looks.
if it's ok with you, could you share the screen shots?
