### ISSUE TITLE
AA_Unlock malfunction

### ISSUE THREAD

**Issue by telattila** [slashmax/AAMirror#40]
Hi there,
With my huawei p9, the AA_Unlock app has some issues. After root grant, the restart phone message does not appear, nothing happens. Pressing the button has no effect.
AA, and GPS are up to date.

Any hint, or help could be useful.
I have tried to find the source of this apk or any info about it, but had no luck.
Thanks.

**Comment by mahouda28** [comment]
hi i have the same issue with gps up to date doesn t work to me may be google have blocked this app doesn t appear in android auto please make resolve this issue.

**Comment by slashmax** [comment]
I think the car module was updated, i'll try to look into it

**Comment by dstarcev** [comment]
Yesterday I installed the latest GPS and Android Auto to a fresh android (resurrection remix firmware). When I tap Unlock, Magisk grants the root to the unlocker and “reboot the phone” toast appears. However AAMirror doesn’t appear in the Android Auto any more. Probably, the latest version of AA brings some changes that AAMirror and Unlocker should respect

**Comment by Jithinsiva** [comment]
Same issue here. Yesterday Ive rooted my phone just for this functionality. It worked well !!!. But after  Google play service and android auto update, today AAmirror doesn't appear in the android auto. I think Google blocked it again. :(

**Comment by slashmax** [comment]
try the latest unlock

**Comment by rokofra** [comment]
Unlock installiert nicht richtig. Nach der Installation Root not available Kan mir einer einen Tipp geben

**Comment by Jobo504** [comment]
Hello,
just tried the new Unlock APK (updated 2 hours ago). Unfortunately AAMirror still doesn't appear. 
Besides from that great work so far!

**Comment by damkas** [comment]
Same Tried the new Unlock APK and don"t work

**Comment by alexfocus** [comment]
Hi. Unfortunately, the new testing unlock (12 hours ago) don"t work

**Comment by alexfocus** [comment]
Thanks, the latest version works very well
