### ISSUE TITLE
Bateri reduction

### ISSUE THREAD

**Issue by LeaderHC** [slashmax/AAMirror#41]
First of all, congratulations for this project! In fact this made a big difference on the Mylink and other devices by your initiative!
I do not now if this is the best place to request, because I do not have experience in these site, but I hope so. My question or request, is about the power of the battery of smartphones in use the AA Mirror Plus, because the app for mirroring in use need the screen light on working and I wonder if it is possible to develop resource for the app working with screen off light, because the same the smartphone plugged in cable, depending on the app running, example iGO, the charging ins't enough.
I tried to reducing lighting of screen, but doesn't work.

**Comment by slashmax** [comment]
As far has i know the screen cant be turned off, just change the brightness to 0 in settings.
