### ISSUE TITLE
The validity aaunlock limited in time

### ISSUE THREAD

**Issue by alexfocus** [slashmax/AAMirror#43]
The new aaunlock is valid for 1 day, then have to apply it again, reboot the device and clear the cache Android Auto. After these operations, AAMirror works normally all day. Can it be fixed?

**Comment by Ierocky** [comment]
Same problem, do you know if the last update fixed it?

**Comment by alexfocus** [comment]
The Chimera is cripled. Everything works perfectly. Thank you

**Comment by jhingansaurabh** [comment]
can someone please tell me what combination of GPS and Android auto versions are you using?

**Comment by alexfocus** [comment]
Android Auto - 3.4.582354, GPS - 12.8.74

**Comment by jhingansaurabh** [comment]
for some reason the screen goes blank when i hit the OEM on my head unit. what am i doing wrong? any inputs/fixes are appreciated.

**Comment by slashmax** [comment]
check phone for permisions

**Comment by jhingansaurabh** [comment]
do i need to allow any app special permissions? please elaborate!
