### ISSUE TITLE
Apk ver. 02/02/2018

### ISSUE THREAD

**Issue by waw555** [slashmax/AAMirror#6]
Applications open
The side menu disappears and appears.
Back button does not work
The sensor of the car does not work, it's more difficult to use the car sensor to control an open application.
The favorites button is now perfectly installed applications.
The Menu button does not work.
The screen in the phone is too dark, you need to either increase a little brightness, or look for another solution.

Sound from the application is not transmitted to the radio, only if notifications arrive in the Android Au to, only then the sound appears and then disappears.

**Comment by vchivu** [comment]
Unusable on non-rooted phones. Sidebar will not show. Screen orientation is locked to portrait (AA default).
First version still works very well on non-rooted. Maybe you could add a fork and have 2 versions, root and no root?

**Comment by kaiserssosse** [comment]
that would be a great idea, one branch for rooted and another one for non-rooted

**Comment by slashmax** [comment]
is same application for root and unrooted. on unrooted phones some features just dont work.
