### ISSUE TITLE
Screen resize (root) (2x)

### ISSUE THREAD

**Issue by Tiemichael** [slashmax/AAMirror#7]
After implementation of the new '	screen resize (root) (2x)'-feature some application content is no longer displayed. It seems that some overlays in applications are missing.
Is there are way to configure (or switch off ) the screen-resizing?
The previous version was working fine for me

(using a Xiaomi A1, with Android 8, rooted, AA in Opel Astra 2017)

**Comment by slashmax** [comment]
i'll try to add a settings page for brightness, rotation and screen size. for now i'm still testing stuff.

**Comment by vchivu** [comment]
Could you please also make sidebar hiding optional in settings?

Victor Chivu
vchivu@gmail.com
*RO:*  +40 722 270 841
