### ISSUE TITLE
No touch interection

### ISSUE THREAD

**Issue by pdario** [slashmax/AAMirror#8]
Hello, I cloned and built the app; when I try to use it on my S8+ (not rooted) and my Ford Sync, I only get the screen mirroring without any touch interaction.
Is this because it need the phone to be rooted or is there something else?

Thank you

**Comment by Tiemichael** [comment]
You need to be rooted for touch interactions inside an application.
The AAMirror  Buttons on the left side should be working

**Comment by pdario** [comment]
I haven't buttons anywhere... should I??

**Comment by kaiserssosse** [comment]
There are apps to able you to put buttons on the screen, for example Back button.

**Comment by Tiemichael** [comment]
@padrio: see the Read.me ..
Try sliding from the left

**Comment by pdario** [comment]
@kaiserssosse: can you please tell me where to find them? Any link or hint?
@Tiemichael: Sliding does not work, I can't interact in anyway

**Comment by joemk2** [comment]
sorry, I have other question.
Thanks for your good idea and aa-mirror
My phone is Lg optimus G pro and Android version is 5.0.1
When I installed android auto app, there was no problem.
But I got this error message whenever try to install aa-mirror
(Parse Error, There is a problem parsing the package.)

LG do not support upgrade version to Optimus G pro anymore.
changing phone is the only way to use this aa-mirror?

**Comment by bobybc** [comment]
`

> @kaiserssosse: can you please tell me where to find them? Any link or hint? @Tiemichael: Sliding does not work, I can't interact in anyway; moreover, the screen is always vertical, it does not rotate
> --
i can confirm that sliding does not work on Android 7 , Samsung S7 no root even with the latest version from today
the left menu shows only on initial start of AAmirror, after a while it disappears and there is no way to slide it back

`

**Comment by vchivu** [comment]
@bobybc switch to another tab and back and the menu will show

Victor Chivu
vchivu@gmail.com
*RO:*  +40 722 270 841

**Comment by pdario** [comment]
@vchivu what tabs do you mean? The ones provided by Android Auto (eg Maps, Telephone, Audio...)?

**Comment by vchivu** [comment]
yes.

Victor Chivu
vchivu@gmail.com
*RO:*  +40 722 270 841

**Comment by slashmax** [comment]
root is required for touch redirect. Sliding from edges should work but the edge is unfortunately very small(u need to slide from the very edge) and the drawer is not very touch friendly because it generates touch cancels that i cant emulate, no alternatives for now.
