### ISSUE TITLE
Black screen in Android 5.0

### ISSUE THREAD

**Issue by kaiserssosse** [slashmax/AAMirror#9]
After connecting and launching the app in AA, que screen of AA went black.

**Comment by slashmax** [comment]
u need to allow application to capture screen. if u dont get the prompt then check for power/autostart apps and add aa mirror to whitelist.

**Comment by kaiserssosse** [comment]
When I installed the app I accept the permissions before install. The second part "if u dont get the prompt then check for power/autostart apps and add aa mirror to whitelist" i didn't know how to do it, I surf on the internet but I don't see nothing related to android.

**Comment by kaiserssosse** [comment]
solved!

**Comment by suby20** [comment]
To. kaserssosse
Can I know how you solved it?
I have the same problem.
